site_name: FeedbackAI-Tool API Documentation
nav:
    - Home: index.md
    - API Reference:
        - Organisation: organisation.md
        - Assignment: assignment.md

theme:
    name: material
plugins:
  - search
  - mkdocstrings

