site_name: FeedbackAI-Tool API Documentation
nav:
    - Home: index.md
    - Getting Started:
        - Installation: installation.md
        - Quick Start:
            - Organisation: quick_start_organisation.md
            - Teacher: quick_start_teacher.md
            - Student: quick_start_student.md
    - API Reference:
        - Organisation: organisation.md
        - Assignment: assignment.md
        - Teacher: teacher.md
        - Student: student.md
        - Course: course.md
    

theme:
    name: material
plugins:
  - search
  - mkdocstrings

dev_addr: 0.0.0.0:8001  # Change the port number here

